FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

# TODO
# Copier le projet et restaurer les dépendances (dotnet restore)
# Copier le code et publier l'application (dotnet publish)
# Utiliser un stage final plus léger (dotnet runtime) et copier les fichiers nécessaires depuis le stage de build

