name: "Publish images to GHCR"

on:
  push:
    branches:
      - github_deploy
    paths:
      - "vote/**"
      - "result/**"
      - "worker/**"
      - ".github/workflows/publish-and-deploy.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_TAG: ${{ github.sha }}
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}/formation-vote

jobs:
  publish-images:
    name: Build and push images to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ github.token }}" | docker login ghcr.io --username "${{ github.actor }}" --password-stdin
      
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >>${GITHUB_ENV}
     
      - name: Build images with dockerfile
        run: |
          docker build -t "$REGISTRY/$REPO/vote:$IMAGE_TAG" -f vote/Dockerfile.ci .
          docker build -t "$REGISTRY/$REPO/result:$IMAGE_TAG" -f result/Dockerfile .
          docker build -t "$REGISTRY/$REPO/worker:$IMAGE_TAG" -f worker/Dockerfile .
  
      - name: Push images
        run: |
          docker image push "$REGISTRY/$REPO/vote:$IMAGE_TAG"
          docker image push "$REGISTRY/$REPO/vote:latest"
          docker image push "$REGISTRY/$REPO/result:$IMAGE_TAG"
          docker image push "$REGISTRY/$REPO/result:latest"
          docker image push "$REGISTRY/$REPO/worker:$IMAGE_TAG"
          docker image push "$REGISTRY/$REPO/worker:latest"

      - name: Print image names
        run: |
          echo "Images publiées :"
          echo "  ghcr.io/$REPO/vote:$IMAGE_TAG"
          echo "  ghcr.io/$REPO/result:$IMAGE_TAG"
          echo "  ghcr.io/$REPO/worker:$IMAGE_TAG"
